
package com.williamsportwebdeveloper;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServicesSoap", targetNamespace = "http://www.williamsportwebdeveloper.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServicesSoap {


    /**
     * Gets the books matching part of a title.
     * 
     * @param strTitle
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBooksByTitle", action = "http://www.williamsportwebdeveloper.com/GetBooksByTitle")
    @WebResult(name = "GetBooksByTitleResult", targetNamespace = "http://www.williamsportwebdeveloper.com/")
    @RequestWrapper(localName = "GetBooksByTitle", targetNamespace = "http://www.williamsportwebdeveloper.com/", className = "com.williamsportwebdeveloper.GetBooksByTitle")
    @ResponseWrapper(localName = "GetBooksByTitleResponse", targetNamespace = "http://www.williamsportwebdeveloper.com/", className = "com.williamsportwebdeveloper.GetBooksByTitleResponse")
    public String getBooksByTitle(
        @WebParam(name = "strTitle", targetNamespace = "http://www.williamsportwebdeveloper.com/")
        String strTitle);

    /**
     * Gets the books matching part of an author's name.
     * 
     * @param strAuthor
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBooksByAuthor", action = "http://www.williamsportwebdeveloper.com/GetBooksByAuthor")
    @WebResult(name = "GetBooksByAuthorResult", targetNamespace = "http://www.williamsportwebdeveloper.com/")
    @RequestWrapper(localName = "GetBooksByAuthor", targetNamespace = "http://www.williamsportwebdeveloper.com/", className = "com.williamsportwebdeveloper.GetBooksByAuthor")
    @ResponseWrapper(localName = "GetBooksByAuthorResponse", targetNamespace = "http://www.williamsportwebdeveloper.com/", className = "com.williamsportwebdeveloper.GetBooksByAuthorResponse")
    public String getBooksByAuthor(
        @WebParam(name = "strAuthor", targetNamespace = "http://www.williamsportwebdeveloper.com/")
        String strAuthor);

}
