
package com.williamsportwebdeveloper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Web services to query the book database.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookServices", targetNamespace = "http://www.williamsportwebdeveloper.com/", wsdlLocation = "http://www.williamsportwebdeveloper.com/BookServices.asmx?WSDL")
public class BookServices
    extends Service
{

    private final static URL BOOKSERVICES_WSDL_LOCATION;
    private final static WebServiceException BOOKSERVICES_EXCEPTION;
    private final static QName BOOKSERVICES_QNAME = new QName("http://www.williamsportwebdeveloper.com/", "BookServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.williamsportwebdeveloper.com/BookServices.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSERVICES_WSDL_LOCATION = url;
        BOOKSERVICES_EXCEPTION = e;
    }

    public BookServices() {
        super(__getWsdlLocation(), BOOKSERVICES_QNAME);
    }

    public BookServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSERVICES_QNAME, features);
    }

    public BookServices(URL wsdlLocation) {
        super(wsdlLocation, BOOKSERVICES_QNAME);
    }

    public BookServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSERVICES_QNAME, features);
    }

    public BookServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookServicesSoap
     */
    @WebEndpoint(name = "BookServicesSoap")
    public BookServicesSoap getBookServicesSoap() {
        return super.getPort(new QName("http://www.williamsportwebdeveloper.com/", "BookServicesSoap"), BookServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookServicesSoap
     */
    @WebEndpoint(name = "BookServicesSoap")
    public BookServicesSoap getBookServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.williamsportwebdeveloper.com/", "BookServicesSoap"), BookServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSERVICES_EXCEPTION!= null) {
            throw BOOKSERVICES_EXCEPTION;
        }
        return BOOKSERVICES_WSDL_LOCATION;
    }

}
